name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: make
  tests-vector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: tests
        run: |
          make
          sudo apt install valgrind -y
          bash scripts/test.vector.sh
  tests-map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: tests
        run: |
          make
          sudo apt install valgrind -y
          bash scripts/test.map.sh
  tests-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: tests-stack
        run: |
          make
          sudo apt install valgrind -y
          bash scripts/test.stack.sh
  tests-others:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: tests-others
        run: |
          make
          sudo apt install valgrind -y
          bash scripts/test.others.sh